### ISSUE TITLE
Error with serialization of play.mvc.Result

### ISSUE THREAD

**Issue by mmolinos** [KarelCemus/play-redis#129]
### Reporting a bug?
1. Version of play-redis --> 1.6.0
2. Version of Java --> 8
3. Version of Play --> 2.6
4. Describe the environment if applies (usually in cloud etc.) --> dockers
5. Describe the expected behavior --> Save Controller with the @Cached annotation
6. Describe the actual behavior, follow the same scenario
7. Provide instructions to reproduce the issue --> Try an controller like this:

```
import play.cache.Cached;
    public class ExamplesApiController extends Controller {

        private final ExamplesApiControllerImpInterface imp;

    @Inject
   @Cached(key = "exampleCache", duration=5*60)
    private ExampleApiController(ExamplesApiControllerImpInterface imp) {
        this.imp = imp;
    }


        @ApiAction
        public CompletionStage<Result> listExample() throws Exception {

            CompletionStage<List<Invoice>> completionStage = imp.example();
                    return completionStage.thenApply(obj -> { 
            JsonNode result = Json.toJson(obj);
                return ok(result);
                });
            
        
            }
        }
```

**Comment by johnsiu** [comment]
Not a play-redis issue per se.
play.mvc.Result is not serializable so using akka.serialization.JavaSerializer will not work.

Try configuring akka to use kryo instead.

See 
https://doc.akka.io/docs/akka/current/scala/serialization.html
https://github.com/romix/akka-kryo-serialization

**Comment by KarelCemus** [comment]
Hi, thank you both for your contribution.

I agree with @johnsiu, thanks for the response. I just add that `play-redis` needs to be agnostic to the implementation of the serialization mechanism because it would be very limiting to enforce some implementation to end users. Thus it fallbacks to the default implementation, which is Java serialization. If the `Result` does not implement `Serializable` as John says so, then you need to implement some other serialization mechanism. Personally, I recommend kryo, which is efficient and easy to use. Look [into the changelog](https://github.com/KarelCemus/play-redis/blob/master/CHANGELOG.md#link-120) for more details. 

Does this solve your issue? Please let us know so we can close it and for a future reference.

**Comment by mmolinos** [comment]
Thanks for all. It's works nice
