### ISSUE TITLE
Configuration on Heroku

### ISSUE THREAD

**Issue by neilchaudhuri** [KarelCemus/play-redis#15]
This is not an "issue," but I was curious if you could provide guidance on how to configure play-redis on Heroku since you only get the full Redis URL rather than the components. I imagine I have to use a provider (I am using Scaldi for dependency injection) to parse the Redis URL, configure play-redis with the components, and inject it as the the CacheApi implementation. Is there anything special I need to do or any suggestions you'd have for doing this while still having play-redis remain the CacheApi implementation? 

Also, is it possible to use CacheApi backed by play-redis in production but CacheApi backed by Ehcache in development?

Thanks.

**Comment by KarelCemus** [comment]
First, I have never used Heroku, so I don't know. I took a brief look into it now and it seems to me that it provides a URL instead of parts in REDIS_URL env variable. So, if I'd add the support of that it should be fine, right? Otherwise give me exact requirements.

So I propose to open an issue to extract the configuration out and create a ConfigurationProvider trait with 2 possible implementations. One (default) would read application configuration and the other (possibly both inside or outside the library) could manage any other source of the configuration. Would this work for you?

Second, I must extend the configuration by authentication. I do not support it right now.

-----

To your last question: I guess so but haven't tested. However, all these are just about application configuration and its modules. It is true this library enables it self by default and disables EHCache but nothing prevents you to overwrite this configuration in your development environment. I'd suggest to read Play manual, there is guidance. Nevertheless you would loose many functions. Standard `play.api.cache.CacheApi` provided by Play itself and implemented by EHCache declares only very basic operations. I extended this API with `play.api.cache.redis.CacheApi` and it provides way more handful operations. However, this is not implemented by EHCache so you cannot use it if you want to combine them.

Also I'm thinking the library does not bind its SyncCache implementation to the Play's CacheApi, only to mine. That should be fixed.

**Comment by neilchaudhuri** [comment]
If you can provide support for full URLs out of the box (in my case on Heroku the REDIS_URL env variable), that would be great. It goes beyond what I was asking for! Your proposed change would work great for me and anyone else deploying to a PaaS.

I'm sure you will handle the authentication and SyncCache binding stuff just fine when you can.

As for the Ehcache in development thing, I am basically just trying to figure out the easiest way to develop/test locally and then test things "for real" on my staging/test server. I would prefer not to have to install Redis locally, and in my particular case, my caching needs are not nearly as sophisticated as that of your other users. So I am looking for the easiest possible approach, and I thought the Ehcache in dev and Redis in staging approach would work. There are other approaches too, and I am sure I can read up on best practices along these lines elsewhere.

Thank you for your help.

**Comment by KarelCemus** [comment]
Hopefully I covered all reported issues so I'm closing this. For more details please follow the newly reported issues.

**Comment by KarelCemus** [comment]
All changes has been published. Feel free to test them.

**Comment by neilchaudhuri** [comment]
Great. Thanks for your hard work. 

Just a small suggestion. Your classes and traits named Heroku* maybe should be renamed to something more generic like with Url* or Env*. Heroku is the cloud provider I am using, but those who deploy to other providers like Microsoft Azure may also have to deal with the same issue (configuration via url). This way it will be more intuitive that the code isn't platform-dependent but rather env var dependent. Of course this is your decision.

Look forward to trying it out. Thanks again.

**Comment by KarelCemus** [comment]
> Just a small suggestion. Your classes and traits named Heroku* maybe should be renamed to something more generic like with Url* or Env*. Heroku is the cloud provider I am using, but those who deploy to other providers like Microsoft Azure may also have to deal with the same issue (configuration via url). This way it will be more intuitive that the code isn't platform-dependent but rather env var dependent. Of course this is your decision.

Well that's true but I'm not sure it would work in other envs, I haven't read their specification. There might be different env variable, no authentication etc. I considered the current impl a bit safer. But I'll think about your suggestion and possibly provide a bit more generic solution.

Thanks for the tip!
