### ISSUE TITLE
Is it possible to get and catch with Generic type

### ISSUE THREAD

**Issue by khacsinhcs** [KarelCemus/play-redis#193]
I'm not sure it is a bug or not. I have a case class

```
trait InternalType
case class Host(name: String) extends InternalType
```

When I tried to get from Redis 

```
trait HasValue[Type <: InternalType] {
    val cache: CacheAsyncApi
    cache get[Type] "someKey"
}
```

Then I got `No ClassTag available for Type`. But if I do `cache get[Host] "someKey"` then everything work as expectation 

How can I get and catch type in this generic way?

**Comment by KarelCemus** [comment]
The issue with your code is, that the `Type` is unknown at compilation of the code, therefore compiler is not able to provide a `ClassTag` for the `Type`, which is essential for the cache to properly unmarshal data.

There are two ways to fix your code, which I see right now.

1. Replace the trait with a class with implicit `ClassTag`

```scala
abstract class HasValue[Type <: InternalType : ClassTag]
```

2. put the get into some `def` accepting the `ClassTag`

```scala
  def getValue(implicit classTag: ClassTag[Type])=cache.get[Type]("someKey")
```

This probably is not what you are looking for but since it is not issue of the play-redis, but limitation of scala and a classtag, I don't think I am able to help you more.
