### ISSUE TITLE
Receive timeout while using redis as cache in play framework

### ISSUE THREAD

**Issue by tanajilondhefidel** [KarelCemus/play-redis#201]
1.libraryDependencies += "com.github.karelcemus" %% "play-redis" % "1.4.0"
2.Version of Java(I am using Play with Java):- 8
3.Version of Play :- 2.5.14
4.Environment :- Webserver nginx and cloud service is AWS
5.Redis configs
  maxmemory is : 7gb
  memorypolicy: all-keylru

6.Actual Behavior

I am using redis as a cache to store data in Play framework application. Redis module is enabled using the following config in application.conf

play.modules.disabled += "play.api.cache.EhCacheModule"
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"

In .classpath I found seredis libraries as:-
<classpathentry kind="lib" path="/home/punam/.ivy2/cache/com.livestream/scredis_2.11/jars/scredis_2.11-2.0.8.jar"/>

I got an error on set and get data in redis cache.

The exact error I am getting in application.log is:-

> [error] s.i.ListenerActor - Receive timeout [error] p.a.cache.redis - Command GET classTag::_cursor_UPDATE_VAL for key 'GET' failed. scredis.exceptions.RedisIOException: Receive timeout to localhost/127.0.0.1:6379 at scredis.io.ListenerActor$$anonfun$reconnecting$1.applyOrElse(ListenerActor.scala:414) at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) at akka.actor.Actor$class.aroundReceive(Actor.scala:497) at scredis.io.ListenerActor.aroundReceive(ListenerActor.scala:27) at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) at akka.actor.dungeon.DeathWatch$class.receivedTerminated(DeathWatch.scala:46) at akka.actor.ActorCell.receivedTerminated(ActorCell.scala:374) at akka.actor.ActorCell.autoReceiveMessage(ActorCell.scala:511) at akka.actor.ActorCell.invoke(ActorCell.scala:494)

I checked /var/log/redis/redis-server.log but the file is empty.

After getting this error frequently, I restarted the redis and was able to set/get data in Redis cache. Redis runs fine for 7-8 days, I am able to set/get data in a cache but after 7-8 days will get the same error again and I have to restart Redis.

Is this due to Redis is not accepting for a new request? Which redis configurations should I change? Should I upgrade libraries, if yes do I need to change the code?

7. Expected Behavior:- Data should be stored in Redis cache even after 7-8 days. It should not throw timeout error.

**Comment by KarelCemus** [comment]
Hi, sorry for late reply.

Your issue is very unspecific so it is difficult to get some conclusion. However, there are few notes:

- You use very old version of play-redis, which is no longer supported (unless some critical issues) and internal scredis connector was deprecated long time ago.
- play-redis itself only delegates your queries to the internal connector (scredis) so it does not deal with the connection management, therefore, I am not much aware of its implementation or its issues.
- since your issue is nearly impossible to reproduce and very probably environment-specific, I don't have any idea how to trace it or help you
- the issue might be both in the scredis or the redis server itself, hard to tell which of these is true. maybe you could test it when the issue occurs again. Try to connect to the redis server manually e.g. via a cli, which could narrow down your issue
- I use play-redis in production applications, which run usually for months without a restart, my personal record is about 6 months without a restart, then the server had to be restarted due to its update. So I don't think this is an issue of the play-redis itself. 

Sorry I could not help you more.
