### ISSUE TITLE
NullPointerException occurs when calling getOptional API of Java

### ISSUE THREAD

**Issue by yamakz5555** [KarelCemus/play-redis#222]
### Version
1. Version of play-redis : 2.5.0
1. Version of Play : 2.7.3
1. Version of JDK : 1.8.0_231

### API 

- play.cache.SyncCacheApi#getOptional

### Expected Behavior

1. API return Optional.empty.

### Actual Behavior

1. NullPointerException occurred.

### Reproducible Test Case

1. Set null data to any key in Redis.
```
@Inject
SyncCacheApi cacheApi;

cacheApi.set("test_key", null, 3600);
```
2. call getOptional API of Java
```
Optional<String> valueOptional = cacheApi. getOptional("test_key");
```

**Comment by yamakz5555** [comment]
I don't know Scala, but I tried debugging.
In the following part, tag is null.
Looks like it's behaving incorrectly

https://github.com/KarelCemus/play-redis/blob/master/src/main/scala/play/api/cache/redis/impl/JavaCompatibility.scala#L69
```
@inline def classTagFrom[T](tag: String)(implicit environment: Environment): ClassTag[T] = {
  if (tag == "") ClassTag.Null.asInstanceOf[ClassTag[T]]
  else ClassTag(classTagNameToClass(tag, environment))
}
```

**Comment by KarelCemus** [comment]
I conducted some tests and there are some results:

First, `tag is null` should not be null if you called `cacheApi.set("test_key", null, 3600);` as you say.

The issue is that it is not much clear what should be the returned value. Consider this:
1. if the value is non-empty and the redis key is set, it returns non-empty option, i.e, `Optional.of("value")`
2. if the value is undefined and the key is not set, it returns `Optional.empty()`
3. if the value is defined but it is `null`, it is not clear what to return and this is your case. 

Since the key is defined, it should be  `Some` but with the value `null`. Therefore, I'd expect something like this `Optional.of(null)`. Unfortunately, this is not valid case since Java implements it as this:

```
    private Optional(T value) {
        this.value = Objects.requireNonNull(value);
    }
```

What are your thoughts on this? I can make it return `Optional.empty()` though I am not sure that this is actually the correct behavior. If anything, it would be either breaking change for Scala users or the Java and Scala API would be inconsistent in the returned value.

**Comment by yamakz5555** [comment]
I understand.
As you said, it cannot be expressed well in Java, and the current API specification cannot distinguish between the absence of a cache and the null value being cached.

However, changing the API specification of getOptional has a big impact. Probably the null value caching itself is not good, but the situation where a NullPointerException occurs is also not appropriate.


There are parts of your description that you did not understand.
If I change to return Optional.empty () in Java, will it affect Scala users?

**Comment by KarelCemus** [comment]
> There are parts of your description that you did not understand.

What have I missed? 

> If I change to return Optional.empty () in Java, will it affect Scala users?

Well, it does not affect them directly though if the Scala API would return `Some(null)` and JAva API would return `Optional.empty`, which is like Scala's `None`, then it would be the inconsistency I mentioned above.

**Comment by KarelCemus** [comment]
I have to apologize, you were right. I did not realize that `set(null)` actually translates to `DEL` command. Therefore there is actually no stored value in the redis, only the classtag indicating to interpret is as a null. And then there was (hopefully) a bug in the decoder transforming an empty string into `null`.

I removed it in #223 and I hope this won't be a breaking change, not sure with that. Could you please test this PR and check if it works for you?

**Comment by KarelCemus** [comment]
Alright, I reconsidered it. I realized that removing translation of `""` to `null` might have significant impact on compatibility, therefore I changed the classtag for `null` values from `"" to `"null"`. It is a bit breaking change but since it was not possible to retrieve the value without getting the NPE, I believe it is pretty much ok.

Thoughts on that? Could you revise and test that PR?
