### ISSUE TITLE
Adding TLS support for redis

### ISSUE THREAD

**Issue by irshadgit** [KarelCemus/play-redis#249]
Redis version 6 now support TLS. Add this support in this library so that TLS enabled redis servers can be used with this library.
https://redis.io/topics/encryption
More details can be found in this [stack overflow issue](https://stackoverflow.com/q/67625493/2788009).

**Comment by irshadgit** [comment]
I have logged the same in stack overflow as well
https://stackoverflow.com/q/67625493/2788009

**Comment by KarelCemus** [comment]
This is just an upper layer above the redis connector therefore there must be some connector fitting the requirements of this library + implementing TLS. At this moment play-redis uses https://github.com/etaty/rediscala or its forks. Feel free to implement this feature in this connector and I can then implement it in play-redis.

Alternatively feel free to participate on providing Jedis connector implementation for play-redis, I assume Jedis supports TLS. https://github.com/KarelCemus/play-redis/issues/248

Unfortunately, I have no time to do it myself but your help would be appreciated.

I closed this issue for now since it is blocked by unavailable connector implementation. Feel free to reopen any time in future when there is Jedis implementation or rediscala supports it.

**Comment by carstenlenz** [comment]
@KarelCemus Hi. I've seen that the underlying lettuce does essentially support TLS but it seems Play-Redis wraps it so well that currently that cannot be enabled. But it should be doable right?

**Comment by KarelCemus** [comment]
If it does support it, feel free to open a PR to this project to expose it. I don't have resources to do it on my own but I am open to reviewing and accepting PRs
