### ISSUE TITLE
Support play-json directly for serialization

### ISSUE THREAD

**Issue by Bugsource** [KarelCemus/play-redis#254]
As web service return json to frontend at most cases, and `play-redis` is aim to serving play framework, so it will be very convenient for developers if `play-redis` support `play-json` serialization directly.

**Comment by KarelCemus** [comment]
Play redis supports akka serializers and you can provide your own serializer by implementing Akka's interface, see [documentation](https://github.com/KarelCemus/play-redis/blob/master/doc/20-configuration.md#limitation-of-data-serialization). There are no current plans for implementing play redis, since you can either implement the serializer or your own wrapper over this API. Play-json is not considered much efficient and performant library, which are the most significant reasons for not providing the implementation by default.
