### ISSUE TITLE
Release 1.5.0 stable for Play 2.6

### ISSUE THREAD

**Issue by KarelCemus** [KarelCemus/play-redis#95]
Forked #89, this issue is focused on finalization of `1.5.0` and make it ready for release

**Comment by KarelCemus** [comment]
@scozv Hi, any progress on this one? How's the testing?

**Comment by scozv** [comment]
Hi @KarelCemus 

With your tips on #96, I finished my `HGET` part with injecting the `play.api.cache.redis.CacheAsyncApi`. Runtime works well now.


I am not familiar with Redis, and in my project, I don't use redis frequently.
However I still have 2 feedbacks / questions for you.

1. in your `README`, you mentioned the value of `play.cache.redis.database` is `1-15`.
But I somehow, I have to connect to database `0`. 

```
[info] p.a.cache.redis - Redis cache actor started. It is connected to localhost:6379?database=0
```

```
// application.conf

play.cache {
  # If you want to bind several caches, you can bind the individually
  #bindCaches = ["db-cache", "user-cache", "session-cache"]
  redis {
    host = "localhost"
    port = "6379"
    database = 0
  }
}
```

So would you please update the document. Because, form you README, I thought the valid value of database number is  only form `1` to `15`


2. How do we use `play-redis` for test.

Test is so import, I tried to write a TestSuit for my code, but `sbt` cannot find any test case there.

```
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
```

here is the Spec file:

```
package nosql.redis

import com.google.inject.Inject
import org.scalatestplus.play._
import org.scalatestplus.play.guice.GuiceOneAppPerTest

class MyClassSpec @Inject() (
  // the MyClass is what I want to test
  // https://github.com/KarelCemus/play-redis/issues/96#issue-236066512
  cache: MyClass 
) extends PlaySpec with GuiceOneAppPerTest {

  "cache test" should {
    "write and read value" in {
      cache.set("a@b.com", "a@b.com-random-token")
      cache.get("a@b.com") mustBe Some("a@b.com-random-token")
      cache.findByValue("a@b.com-random-token") mustBe Some("a@b.com")
    }
  }
}
```

I read the test code in your `play-redis/src/test/scala`, but I can not use the helper class in your test folder.

So is there any easy way that I can use `play-redis` in my test suit?

Thanks

**Comment by KarelCemus** [comment]
Hi,

sorry for late response, I was on vacation. 

Thanks for the note, I'll update (simplify) docs. There is no need to duplicate official redis documentation.

Regarding the tests:

1. the helpers you are trying to use are designed only for `play-redis` to help test the library
2. I want to do major test refactoring and simplification, they are awful and slow right now
3. I am not sure there is need for exposing these helpers. I believe you do not have to test the `play-redis` yourself when the tests are already included in the library. And I don't see any other use of these helpers.

So, to you think the lib is ready to be released?

**Comment by scozv** [comment]
for me I think you can release this lib for Play 2.6, cause Play 2.6 (not M1, or C1 version) just release recently. There is no blocked issue for releasing 1.5.0.

However, I just run the test provided in your lib, I noticed:

* there are some compile warning in your lib, such as:

```
ImplementationModule.scala:66: trait CacheApi in package cache is deprecated (since 2.6.0): Use SyncCacheApi or AsyncCacheApi instead
[warn]     bind[ play.api.cache.CacheApi ].to[ play.api.cache.DefaultSyncCacheApi ],
```

* The code coverage is 81~85% (see attachment, extract zip file and open `index.html`), if you want, you can improve the coverage rate.

[scoverage-report.zip](https://github.com/KarelCemus/play-redis/files/1102036/scoverage-report.zip)

**Comment by KarelCemus** [comment]
I know about the deprecations, it's a feature for smoother migration - play-redis still supports old APIs as well as Play itself supports them. I will remove them in a future.

The tests are really bad right now. Too many of them, poor mocking, bad performance etc. They are a major issue right now.

Thanks for your efforts, I will release the lib later today.

**Comment by KarelCemus** [comment]
Released
